export const mockUsers = [
  {
    id: 1,
    name: "Fifine Wintour",
    email: "fwintour0@cisco.com",
    phoneNo: "659-558-3919",
    username: "fwintour0",
    role: "Consultant Manager",
  },
  {
    id: 2,
    name: "Jerrylee Kearton",
    email: "jkearton1@wp.com",
    phoneNo: "890-310-0839",
    username: "jkearton1",
    role: "Consultant",
  },
  {
    id: 3,
    name: "Goldarina Byatt",
    email: "gbyatt2@unc.edu",
    phoneNo: "507-393-0340",
    username: "gbyatt2",
    role: "Consultant Manager",
  },
  {
    id: 4,
    name: "Cass Middler",
    email: "cmiddler3@wordpress.com",
    phoneNo: "479-745-1982",
    username: "cmiddler3",
    role: "Project Owner",
  },
  {
    id: 5,
    name: "Laurent Radsdale",
    email: "lradsdale4@alibaba.com",
    phoneNo: "955-651-2485",
    username: "lradsdale4",
    role: "Interior Designer",
  },
  {
    id: 6,
    name: "Omar Coil",
    email: "ocoil5@globo.com",
    phoneNo: "946-787-7420",
    username: "ocoil5",
    role: "Project Manager",
  },
  {
    id: 7,
    name: "Worthy Antoinet",
    email: "wantoinet6@dmoz.org",
    phoneNo: "349-148-9299",
    username: "wantoinet6",
    role: "Contractor",
  },
  {
    id: 8,
    name: "Tera Drei",
    email: "tdrei7@yellowpages.com",
    phoneNo: "560-574-5333",
    username: "tdrei7",
    role: "Consultant Manager",
  },
  {
    id: 9,
    name: "Tad Foldes",
    email: "tfoldes8@sogou.com",
    phoneNo: "628-323-0510",
    username: "tfoldes8",
    role: "Project Owner",
  },
  {
    id: 10,
    name: "Wallace Teese",
    email: "wteese9@usa.gov",
    phoneNo: "640-558-8349",
    username: "wteese9",
    role: "Customer",
  },
  {
    id: 11,
    name: "Thornie Cramer",
    email: "tcramera@samsung.com",
    phoneNo: "619-183-2883",
    username: "tcramera",
    role: "Project Owner",
  },
  {
    id: 12,
    name: "Daria Mossman",
    email: "dmossmanb@hexun.com",
    phoneNo: "763-197-5201",
    username: "dmossmanb",
    role: "Suppliers Staff Panel",
  },
  {
    id: 13,
    name: "Neale Drakes",
    email: "ndrakesc@gov.uk",
    phoneNo: "283-494-0089",
    username: "ndrakesc",
    role: "Suppliers Staff Panel",
  },
  {
    id: 14,
    name: "Odele Playford",
    email: "oplayfordd@purevolume.com",
    phoneNo: "201-312-2592",
    username: "oplayfordd",
    role: "Suppliers Staff Panel",
  },
  {
    id: 15,
    name: "Leonidas Rolfini",
    email: "lrolfinie@vinaora.com",
    phoneNo: "902-814-5470",
    username: "lrolfinie",
    role: "Contractor",
  },
  {
    id: 16,
    name: "Morgen McGlaud",
    email: "mmcglaudf@amazon.co.jp",
    phoneNo: "633-480-0695",
    username: "mmcglaudf",
    role: "Consultant Manager",
  },
  {
    id: 17,
    name: "Silvano Yeskov",
    email: "syeskovg@addtoany.com",
    phoneNo: "215-818-3963",
    username: "syeskovg",
    role: "Project Manager",
  },
  {
    id: 18,
    name: "Piotr Wainer",
    email: "pwainerh@rakuten.co.jp",
    phoneNo: "517-859-2526",
    username: "pwainerh",
    role: "Project Owner",
  },
  {
    id: 19,
    name: "Leigh Baccup",
    email: "lbaccupi@npr.org",
    phoneNo: "242-985-7255",
    username: "lbaccupi",
    role: "Consultant",
  },
  {
    id: 20,
    name: "Roland Knapman",
    email: "rknapmanj@archive.org",
    phoneNo: "937-319-3699",
    username: "rknapmanj",
    role: "Suppliers Staff Panel",
  },
];
