export const mockData = [
  //   {
  //     id: "12-6852675",
  //     email: "mlaise0@blog.com",
  //     companyName: "Satterfield-Reinger",
  //     phoneNo: "622-627-2364",
  //     projects: [{}, {}, {}],
  //   },
  //   {
  //     id: "54-9834958",
  //     email: "bobruen1@wikipedia.org",
  //     companyName: "Reynolds, Hilpert and Smitham",
  //     phoneNo: "339-203-7830",
  //     projects: [{}, {}, {}],
  //   },
  //   {
  //     id: "90-9459356",
  //     email: "rgoldfinch2@exblog.jp",
  //     companyName: "Brakus-Botsford",
  //     phoneNo: "432-565-6187",
  //     projects: [],
  //   },
  //   {
  //     id: "32-3912123",
  //     email: "rsnarr3@merriam-webster.com",
  //     companyName: "Howell, Kunze and Pfannerstill",
  //     phoneNo: "490-846-9339",
  //     projects: [{}, {}, {}, {}],
  //   },
  //   {
  //     id: "97-9985160",
  //     email: "rcompfort4@admin.ch",
  //     companyName: "Hand, Barton and Wilkinson",
  //     phoneNo: "204-668-2668",
  //     projects: [{}],
  //   },
  //   {
  //     id: "72-4936844",
  //     email: "dlife5@arizona.edu",
  //     companyName: "Renner-Bosco",
  //     phoneNo: "661-664-4195",
  //     projects: [],
  //   },
  //   {
  //     id: "13-1242122",
  //     email: "cmcgurk6@ibm.com",
  //     companyName: "Wolf Inc",
  //     phoneNo: "832-361-8846",
  //     projects: [{}],
  //   },
  //   {
  //     id: "23-8204823",
  //     email: "ssambrook7@freewebs.com",
  //     companyName: "Brakus-Harber",
  //     phoneNo: "381-104-2899",
  //     projects: [{}, {}, {}],
  //   },
  //   {
  //     id: "99-5671681",
  //     email: "odarleston8@yandex.ru",
  //     companyName: "Ruecker-Gutmann",
  //     phoneNo: "903-669-3449",
  //     projects: [],
  //   },
  //   {
  //     id: "74-4840377",
  //     email: "abuckoke9@go.com",
  //     companyName: "Hansen-Kuhn",
  //     phoneNo: "595-253-7034",
  //     projects: [],
  //   },
  //   {
  //     id: "86-7250669",
  //     email: "hskaifedingerthorpea@addtoany.com",
  //     companyName: "Strosin Group",
  //     phoneNo: "959-353-1344",
  //     projects: [{}, {}, {}, {}],
  //   },
  //   {
  //     id: "15-7255373",
  //     email: "rmcnivenb@google.cn",
  //     companyName: "Wuckert, Hauck and Franecki",
  //     phoneNo: "864-993-8594",
  //     projects: [{}, {}, {}, {}, {}],
  //   },
  //   {
  //     id: "06-0857615",
  //     email: "aswaislandc@storify.com",
  //     companyName: "Bins, Dooley and Tillman",
  //     phoneNo: "624-189-1596",
  //     projects: [{}, {}, {}, {}, {}],
  //   },
  //   {
  //     id: "72-3888454",
  //     email: "gjerischd@gov.uk",
  //     companyName: "Dicki, Cole and Windler",
  //     phoneNo: "193-741-5072",
  //     projects: [{}, {}, {}],
  //   },
  {
    id: "09-1033833",
    email: "ablasdalee@livejournal.com",
    companyName: "Daugherty and Sons",
    phoneNo: "880-177-0621",
    address: "#82, Lorem Ipsum, Lorem, Ipsum",
    projects: [{}, {}, {}],
  },
  {
    id: "04-3299299",
    email: "lcoddf@com.com",
    companyName: "Mertz and Sons",
    address: "#82, Lorem Ipsum, Lorem, Ipsum",
    phoneNo: "838-768-7744",
    projects: [],
  },
  {
    id: "29-2188268",
    email: "fmilesapg@statcounter.com",
    companyName: "Bayer, Altenwerth and Schmidt",
    address: "#82, Lorem Ipsum, Lorem, Ipsum",
    phoneNo: "582-501-3247",
    projects: [{}],
  },
  {
    id: "80-5567387",
    email: "fmcclintonh@state.gov",
    companyName: "Rosenbaum, Schneider and Witting",
    address: "#82, Lorem Ipsum, Lorem, Ipsum",
    phoneNo: "138-268-9024",
    projects: [{}, {}, {}],
  },
  {
    id: "04-3674446",
    email: "coduggani@youku.com",
    companyName: "Kris-Mueller",
    address: "#82, Lorem Ipsum, Lorem, Ipsum",
    phoneNo: "873-326-9810",
    projects: [{}, {}, {}, {}],
  },
  {
    id: "37-7821538",
    email: "epoatej@ocn.ne.jp",
    companyName: "Weimann, Mann and Reinger",
    address: "#82, Lorem Ipsum, Lorem, Ipsum",
    phoneNo: "899-714-9329",
    projects: [{}, {}, {}],
  },
];
