export const mockProjects = [
  {
    id: 1,
    projectName: "Alpha",
    consultant: "Osbert Pindar",
    pointOfContact: "Gennifer Dumbelton",
    projectLocation: "20th Floor",
    tasks: [
      {
        id: 9,
        taskName: "Zamit",
        description:
          "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
        cost: "$62.19",
        startDate: "9/4/2022",
        completionDate: "7/27/2023",
        contractor: "Piotr Winfindale",
        status: "completed",
        tag: ["carpentry"],
      },
      {
        id: 10,
        taskName: "Otcom",
        description:
          "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
        cost: "$63.56",
        startDate: "8/20/2023",
        completionDate: "3/3/2023",
        contractor: "Min Dillingston",
        status: "completed",
        tag: ["electrical"],
      },
    ],
  },
  {
    id: 2,
    projectName: "Zaam-Dox",
    consultant: "Johnna Lettsom",
    pointOfContact: "Lesly Carnow",
    projectLocation: "PO Box 64684",
    tasks: [
      {
        id: 7,
        taskName: "Biodex",
        description:
          "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
        cost: "$56.76",
        startDate: "5/20/2023",
        completionDate: "12/12/2022",
        contractor: "Colette Moynham",
        status: "completed",
        tag: ["electrical"],
      },
      {
        id: 8,
        taskName: "Cookley",
        description:
          "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
        cost: "$61.14",
        startDate: "10/13/2022",
        completionDate: "2/18/2023",
        contractor: "Jervis Parncutt",
        status: "in progress",
        tag: ["carpentry"],
      },
      {
        id: 9,
        taskName: "Zamit",
        description:
          "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
        cost: "$62.19",
        startDate: "9/4/2022",
        completionDate: "7/27/2023",
        contractor: "Piotr Winfindale",
        status: "completed",
        tag: ["electrical"],
      },
      {
        id: 10,
        taskName: "Otcom",
        description:
          "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
        cost: "$63.56",
        startDate: "8/20/2023",
        completionDate: "3/3/2023",
        contractor: "Min Dillingston",
        status: "completed",
        tag: ["carpentry"],
      },
    ],
  },
  {
    id: 3,
    projectName: "Hatity",
    consultant: "Olympie Troup",
    pointOfContact: "Selby Skeldon",
    projectLocation: "8th Floor",
    tasks: [
      {
        id: 4,
        taskName: "Stronghold",
        description:
          "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.",
        cost: "$83.72",
        startDate: "8/24/2023",
        completionDate: "3/15/2023",
        contractor: "Nial Bamfield",
        status: "to do",
        tag: ["piping"],
      },
      {
        id: 5,
        taskName: "Trippledex",
        description:
          "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
        cost: "$50.94",
        startDate: "7/30/2023",
        completionDate: "7/10/2023",
        contractor: "Cleo Francesch",
        status: "in progress",
        tag: ["lighting"],
      },
      {
        id: 6,
        taskName: "Fixflex",
        description:
          "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
        cost: "$73.63",
        startDate: "3/2/2023",
        completionDate: "1/27/2023",
        contractor: "Rockey Brason",
        status: "to do",
        tag: ["piping"],
      },
      {
        id: 7,
        taskName: "Biodex",
        description:
          "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
        cost: "$56.76",
        startDate: "5/20/2023",
        completionDate: "12/12/2022",
        contractor: "Colette Moynham",
        status: "completed",
        tag: ["lighting"],
      },
      {
        id: 8,
        taskName: "Cookley",
        description:
          "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
        cost: "$61.14",
        startDate: "10/13/2022",
        completionDate: "2/18/2023",
        contractor: "Jervis Parncutt",
        status: "in progress",
        tag: ["lighting"],
      },
    ],
  },
  {
    tag: ["carpentry"],
    id: 4,
    projectName: "Gembucket",
    consultant: "Edwin Lochran",
    pointOfContact: "Douglass Benduhn",
    projectLocation: "Suite 57",
    tasks: [
      {
        id: 1,
        taskName: "Konklab",
        description:
          "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
        cost: "$63.29",
        startDate: "10/8/2022",
        completionDate: "11/24/2022",
        contractor: "Sherwood McVeigh",
        status: "completed",
        tag: ["piping"],
      },
      {
        id: 2,
        taskName: "Pannier",
        description:
          "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
        cost: "$95.32",
        startDate: "7/12/2023",
        completionDate: "1/2/2023",
        contractor: "Karlotta Oakman",
        status: "completed",
        tag: ["electrical"],
      },
      {
        id: 3,
        taskName: "Stringtough",
        description:
          "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
        cost: "$76.00",
        startDate: "7/25/2023",
        completionDate: "5/23/2023",
        contractor: "Star Sapp",
        status: "completed",
        tag: ["piping"],
      },
    ],
  },
  {
    id: 5,
    projectName: "Duobam",
    consultant: "Leon Pool",
    pointOfContact: "Marlon Hammatt",
    projectLocation: "3rd Floor",
    tasks: [
      {
        id: 1,
        taskName: "Konklab",
        description:
          "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
        cost: "$63.29",
        startDate: "10/8/2022",
        completionDate: "11/24/2022",
        contractor: "Sherwood McVeigh",
        status: "completed",
        tag: ["lighting"],
      },
      {
        id: 2,
        taskName: "Pannier",
        description:
          "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
        cost: "$95.32",
        startDate: "7/12/2023",
        completionDate: "1/2/2023",
        contractor: "Karlotta Oakman",
        status: "completed",
        tag: ["carpentry"],
      },
      {
        id: 3,
        taskName: "Stringtough",
        description:
          "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
        cost: "$76.00",
        startDate: "7/25/2023",
        completionDate: "5/23/2023",
        contractor: "Star Sapp",
        status: "completed",
        tag: ["carpentry"],
      },
    ],
  },
  {
    id: 6,
    projectName: "Overhold",
    consultant: "Luther Gardener",
    pointOfContact: "Calvin Rushmere",
    projectLocation: "10th Floor",
    tasks: [
      {
        id: 1,
        taskName: "Konklab",
        description:
          "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
        cost: "$63.29",
        startDate: "10/8/2022",
        completionDate: "11/24/2022",
        contractor: "Sherwood McVeigh",
        status: "completed",
        tag: ["lighting"],
      },
      {
        id: 2,
        taskName: "Pannier",
        description:
          "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
        cost: "$95.32",
        startDate: "7/12/2023",
        completionDate: "1/2/2023",
        contractor: "Karlotta Oakman",
        status: "completed",
        tag: ["carpentry"],
      },
      {
        id: 3,
        taskName: "Stringtough",
        description:
          "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
        cost: "$76.00",
        startDate: "7/25/2023",
        completionDate: "5/23/2023",
        contractor: "Star Sapp",
        status: "completed",
        tag: ["electrical"],
      },
      {
        id: 4,
        taskName: "Stronghold",
        description:
          "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.",
        cost: "$83.72",
        startDate: "8/24/2023",
        completionDate: "3/15/2023",
        contractor: "Nial Bamfield",
        status: "to do",
        tag: ["piping"],
      },
      {
        id: 5,
        taskName: "Trippledex",
        description:
          "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
        cost: "$50.94",
        startDate: "7/30/2023",
        completionDate: "7/10/2023",
        contractor: "Cleo Francesch",
        status: "in progress",
        tag: ["lighting"],
      },
      {
        id: 6,
        taskName: "Fixflex",
        description:
          "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
        cost: "$73.63",
        startDate: "3/2/2023",
        completionDate: "1/27/2023",
        contractor: "Rockey Brason",
        status: "to do",
        tag: ["lighting"],
      },
      {
        id: 7,
        taskName: "Biodex",
        description:
          "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
        cost: "$56.76",
        startDate: "5/20/2023",
        completionDate: "12/12/2022",
        contractor: "Colette Moynham",
        status: "completed",
        tag: ["carpentry"],
      },
      {
        id: 8,
        taskName: "Cookley",
        description:
          "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
        cost: "$61.14",
        startDate: "10/13/2022",
        completionDate: "2/18/2023",
        contractor: "Jervis Parncutt",
        status: "in progress",
        tag: ["painting"],
      },
    ],
  },
];
