export const mockProjects = [
  {
    id: 1,
    projectName: "Alpha",
    consultant: "Osbert Pindar",
    pointOfContact: "Gennifer Dumbelton",
    projectLocation: "20th Floor",
    tasks: [{}, {}, {}, {}],
  },
  {
    id: 2,
    projectName: "Zaam-Dox",
    consultant: "Johnna Lettsom",
    pointOfContact: "Lesly Carnow",
    projectLocation: "PO Box 64684",
    tasks: [{}, {}, {}, {}, {}],
  },
  {
    id: 3,
    projectName: "Hatity",
    consultant: "Olympie Troup",
    pointOfContact: "Selby Skeldon",
    projectLocation: "8th Floor",
    tasks: [{}, {}, {}, {}, {}],
  },
  {
    id: 4,
    projectName: "Gembucket",
    consultant: "Edwin Lochran",
    pointOfContact: "Douglass Benduhn",
    projectLocation: "Suite 57",
    tasks: [{}, {}, {}, {}, {}],
  },
  {
    id: 5,
    projectName: "Duobam",
    consultant: "Leon Pool",
    pointOfContact: "Marlon Hammatt",
    projectLocation: "3rd Floor",
    tasks: [{}, {}, {}, {}],
  },
  {
    id: 6,
    projectName: "Overhold",
    consultant: "Luther Gardener",
    pointOfContact: "Calvin Rushmere",
    projectLocation: "10th Floor",
    tasks: [{}, {}, {}, {}],
  },
];
